const fs=require('node:fs'), path=require('node:path'), cp=require('node:child_process');
const root=process.cwd(), base=path.join(root,'node_modules/sql-formatter/dist/cjs');
const {format}=require(path.join(base,'index.js'));
const {postgresql}=require(path.join(base,'languages/postgresql/postgresql.formatter.js'));
const {createDialect}=require(path.join(base,'dialect.js'));
const tokenizer=createDialect(postgresql).tokenizer;
const words=Object.entries(postgresql.tokenizerOptions).filter(([k])=>k.startsWith('reserved')).flatMap(([,v])=>v);
const sqls=[...new Set(words)].map(word=>word.toLowerCase()+' sample');
sqls.push(
  'select count(*),cast(x as integer),current_date,coalesce(x,1),a::timestamp with time zone from MyTable;',
  'create table t (id integer generated by default as identity primary key, x timestamp without time zone);',
  'select t.select,t./*x*/case,t.current_date,public.count(*),select$Id from t;',
  'select case when x is not null then a else b end from t order by x nulls first;',
  'select left(x,1) from a left join b on a.id=b.id;',
  'select x from t group /* boundary */ by x;',
  'select :select,$1;'
);
const native=cp.execFileSync('/private/tmp/dbunk-keyword-probe-20261003',{input:sqls.join('\0')+'\0',encoding:'utf8',maxBuffer:16*1024*1024}).split('\0');
const lex=s=>tokenizer.tokenize(s).map(t=>[t.type,t.type.startsWith('RESERVED_')?t.raw.replace(/\s+/g,' '):t.raw]);
const results=sqls.map((sql,i)=>{
  let baseline;try{baseline=format(sql,{language:'postgresql',keywordCase:'upper',tabWidth:2,useTabs:false,linesBetweenQueries:2});}catch(e){return {sql,native:native[i],baselineError:e.message.split("\n")[0]};}
  if(native[i].startsWith('!ERROR!'))return{sql,baseline,nativeError:native[i]};
  try{return{sql,baseline,native:native[i],sameTokens:JSON.stringify(lex(baseline))===JSON.stringify(lex(native[i]))};}catch(e){return{sql,baseline,native:native[i],comparisonError:e.message};}
});
fs.writeFileSync('plans/evidence/029/keyword-format-source-checks/baseline-comparison.json',JSON.stringify(results,null,2)+'\n');
const summary={cases:results.length,matching:results.filter(r=>r.sameTokens===true).length,mismatches:results.filter(r=>r.sameTokens===false),baselineRefused:results.filter(r=>r.baselineError).length,nativeRefused:results.filter(r=>r.nativeError||r.native?.startsWith('!ERROR!')).length,comparisonErrors:results.filter(r=>r.comparisonError).length};
fs.writeFileSync('plans/evidence/029/keyword-format-source-checks/baseline-summary.json',JSON.stringify(summary,null,2)+'\n');
console.log(JSON.stringify(summary,null,2));
