//! Generator unit tests: column operations.

use super::*;

#[test]
fn renders_column_operations_and_tagged_defaults() {
    let literal = statement(PgObjectOp::SetColumnDefault(SetColumnDefaultOp {
        schema: "lifecycle".into(),
        table: "orders".into(),
        name: "status".into(),
        default: Some(PgDefaultValue::Literal {
            value: "now()".into(),
        }),
    }));
    let expression = statement(PgObjectOp::SetColumnDefault(SetColumnDefaultOp {
        schema: "lifecycle".into(),
        table: "orders".into(),
        name: "created_at".into(),
        default: Some(PgDefaultValue::Expression {
            sql: "now()".into(),
        }),
    }));
    assert!(literal.sql.ends_with("SET DEFAULT E'now()';"));
    assert!(expression.sql.ends_with("SET DEFAULT (now());"));

    assert!(statement(PgObjectOp::AlterColumnType(AlterColumnTypeOp {
        schema: "lifecycle".into(),
        table: "orders".into(),
        name: "amount".into(),
        new_type: "numeric(12, 2)".into(),
        using: Some("amount::numeric".into()),
    }))
    .sql
    .contains("TYPE numeric(12, 2) USING amount::numeric"));

    let variants = vec![
        PgObjectOp::AddColumn(AddColumnOp {
            schema: "lifecycle".into(),
            table: "orders".into(),
            column: NewColumnSpec {
                name: "note".into(),
                data_type: "text".into(),
                nullable: false,
                default: Some(PgDefaultValue::Literal {
                    value: "'quoted'".into(),
                }),
                identity: None,
            },
        }),
        PgObjectOp::DropColumn(DropColumnOp {
            schema: "lifecycle".into(),
            table: "orders".into(),
            name: "note".into(),
            cascade: false,
        }),
        PgObjectOp::RenameColumn(RenameColumnOp {
            schema: "lifecycle".into(),
            table: "orders".into(),
            name: "note".into(),
            new_name: "memo".into(),
        }),
        PgObjectOp::SetColumnNullable(SetColumnNullableOp {
            schema: "lifecycle".into(),
            table: "orders".into(),
            name: "note".into(),
            nullable: false,
        }),
        PgObjectOp::SetColumnDefault(SetColumnDefaultOp {
            schema: "lifecycle".into(),
            table: "orders".into(),
            name: "note".into(),
            default: None,
        }),
    ];
    let preview = generate_object_ddl(&variants).expect("column DDL");
    assert_eq!(preview.statements.len(), variants.len());
    assert!(preview.statements[0].sql.contains("DEFAULT E'''quoted'''"));
    assert!(preview.statements[1].sql.ends_with("RESTRICT;"));
}

#[test]
fn add_column_renders_identity() {
    let op = PgObjectOp::AddColumn(AddColumnOp {
        schema: "s".into(),
        table: "t".into(),
        column: NewColumnSpec {
            name: "id".into(),
            data_type: "integer".into(),
            nullable: false,
            default: None,
            identity: Some(PgIdentity::ByDefault),
        },
    });
    let preview = generate_object_ddl(&[op]).expect("identity column");
    assert_eq!(
        preview.statements[0].sql,
        "ALTER TABLE \"s\".\"t\" ADD COLUMN \"id\" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY;"
    );
    // Older payloads without the field still decode.
    let decoded: NewColumnSpec =
        serde_json::from_str(r#"{"name":"c","dataType":"text","nullable":true,"default":null}"#)
            .expect("legacy column spec");
    assert_eq!(decoded.identity, None);
}
