use super::*;

#[test]
fn endpoints_are_bounded_and_must_share_a_resolved_connection() {
    let e = Endpoint {
        connection_id: "one".into(),
        schema: "a".into(),
    };
    assert!(validate_endpoints("one", &[(Side::Source, &e), (Side::Target, &e)]).is_ok());
    assert_eq!(
        validate_endpoints("other", &[(Side::Source, &e)]),
        Err(CompareError::InvalidRequest)
    );
    assert_eq!(
        validate_endpoints("one", &[]),
        Err(CompareError::InvalidRequest)
    );
}

#[tokio::test]
async fn cancellation_and_deadline_wrap_pending_work() {
    let (tx, rx) = watch::channel(false);
    let control = CaptureControl::new(Instant::now() + Duration::from_secs(60), rx);
    tx.send(true).unwrap();
    assert_eq!(
        control.wait(std::future::pending::<()>()).await,
        Err(CompareError::Cancelled)
    );
    let (_tx, rx) = watch::channel(false);
    let control = CaptureControl::new(Instant::now(), rx);
    assert_eq!(
        control.wait(std::future::pending::<()>()).await,
        Err(CompareError::DeadlineExceeded)
    );
}

fn fixture_spec(port: u16) -> ResolvedPostgresConnectSpec {
    ResolvedPostgresConnectSpec {
        connection_id: "capture-fixture".into(),
        host: "127.0.0.1".into(),
        port,
        database: "schema_compare_native".into(),
        user: "postgres".into(),
        password: String::new(),
        tls: crate::postgres::tls::ResolvedTls::with_mode("127.0.0.1", crate::PgTlsMode::Disable),
        connect_timeout: Some(Duration::from_secs(5)),
        keepalive: None,
        driver_options: Default::default(),
        safety_policy: Default::default(),
    }
}

fn field<'a>(capture: &'a CapturedEndpoint, table: &str, path: FieldPath) -> &'a CapturedValue {
    &capture
        .fields()
        .iter()
        .find(|f| capture.table(f.table_oid).unwrap().identity.name == table && f.path == path)
        .unwrap_or_else(|| panic!("missing {table} {path:?}"))
        .value
}

#[tokio::test]
#[ignore = "run infrastructure/test-db/schema-compare/native.py; owned disposable fixture only"]
async fn native_capture() {
    use super::super::normalize::Fact;
    let port = std::env::var("DBUNK_SCHEMA_COMPARE_TEST_PORT")
        .expect("use native.py")
        .parse()
        .unwrap();
    let spec = fixture_spec(port);
    let admin = dedicated::connect(&spec, dedicated::NoticeSink::Ignore)
        .await
        .unwrap();
    for schema in ["Source", "Target"] {
        admin.client.batch_execute(&format!(r#"
          CREATE SCHEMA "{schema}";
          CREATE TABLE "{schema}".parents (tenant integer, id integer, PRIMARY KEY(tenant,id));
          CREATE TABLE "{schema}".orders (
            tenant integer DEFAULT 7, id integer GENERATED BY DEFAULT AS IDENTITY,
            dropped text, "Quoted name" text DEFAULT 'Source.literal', quantity integer DEFAULT 2,
            total numeric(20,4) GENERATED ALWAYS AS (quantity + 1) STORED,
            matrix integer[][], custom int4range, CONSTRAINT positive CHECK (quantity > 0) NO INHERIT,
            CONSTRAINT fk FOREIGN KEY(tenant,id) REFERENCES "{schema}".parents(tenant,id)
              ON UPDATE CASCADE ON DELETE SET NULL (id) DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT uq UNIQUE NULLS NOT DISTINCT (quantity) INCLUDE (id) DEFERRABLE,
            CONSTRAINT exclusion_window EXCLUDE USING gist
              (custom WITH &&, (int4range(quantity, quantity + 1)) WITH &&));
          ALTER TABLE "{schema}".orders DROP COLUMN dropped;
          CREATE INDEX mixed ON "{schema}".orders (quantity DESC NULLS LAST, (quantity+2)) INCLUDE (tenant) WHERE quantity>0;
          CREATE INDEX multiple ON "{schema}".orders ((quantity+1), (quantity+2));
          CREATE INDEX range_idx ON "{schema}".orders USING gist(custom);
          COMMENT ON COLUMN "{schema}".orders.quantity IS 'quantity comment';
          CREATE TABLE "{schema}".inherited (extra integer) INHERITS ("{schema}".parents);
          CREATE TABLE "{schema}".partitioned (id integer) PARTITION BY RANGE(id);
          CREATE TABLE "{schema}".partition_child PARTITION OF "{schema}".partitioned FOR VALUES FROM (0) TO (10);
          CREATE VIEW "{schema}".view_only AS SELECT 1 AS id;
        "#)).await.unwrap();
    }
    // Parents are deliberately inherited/excluded but still FK references.
    let source = Endpoint {
        connection_id: spec.connection_id.clone(),
        schema: "Source".into(),
    };
    let target = Endpoint {
        connection_id: spec.connection_id.clone(),
        schema: "Target".into(),
    };
    let (tx, rx) = watch::channel(false);
    let control = CaptureControl::new(Instant::now() + Duration::from_secs(60), rx);
    let budget = Budget::default();
    let captures = capture_resolved(
        &spec,
        &[(Side::Source, &source), (Side::Target, &target)],
        &control,
        &budget,
    )
    .await
    .unwrap();
    let (s, t) = (&captures[0], &captures[1]);
    assert_eq!(s.metadata.captured_at, t.metadata.captured_at);
    assert!(s.coverage.excluded_relations >= 4);
    assert!(s
        .inventory
        .iter()
        .any(|row| row.identity.name == "partition_child"
            && row.eligibility
                == Eligibility::Excluded {
                    reason: Exclusion::Partitioned
                }));
    let column = |name: &str, field| FieldPath::Column {
        name: name.into(),
        field,
    };
    assert_eq!(
        field(s, "orders", column("Quoted name", ColumnField::Position)).fact(160015, 160015),
        Fact::Integer(3)
    );
    assert_eq!(
        field(s, "orders", column("matrix", ColumnField::ArrayDimensions)).fact(160015, 160015),
        Fact::Integer(2)
    );
    assert_eq!(
        field(s, "orders", column("quantity", ColumnField::Default)).fact(160015, 160015),
        Fact::Text("2")
    );
    assert!(matches!(
        field(s, "orders", column("quantity", ColumnField::Default)).fact(160015, 160014),
        Fact::NotComparable {
            reason: IncomparableReason::RenderingVersionDifference,
            ..
        }
    ));
    assert_eq!(
        field(s, "orders", column("id", ColumnField::Identity)).fact(160015, 160015),
        Fact::Text("byDefault")
    );
    assert_eq!(
        field(s, "orders", column("quantity", ColumnField::Comment)).fact(160015, 160015),
        Fact::Text("quantity comment")
    );
    let constraint = |name: &str, field| FieldPath::Constraint {
        name: name.into(),
        field,
    };
    assert_eq!(
        field(
            s,
            "orders",
            constraint("fk", ConstraintField::DeleteColumns)
        )
        .fact(160015, 160015),
        Fact::Names(&["id".into()])
    );
    assert!(
        matches!(field(s,"orders",constraint("fk",ConstraintField::EqualityOperators)),CapturedValue::Operators(ops) if ops.len()==6)
    );
    assert_eq!(
        field(
            s,
            "orders",
            constraint("positive", ConstraintField::Expression)
        )
        .fact(160015, 160015),
        Fact::Text("(quantity > 0)")
    );
    let pg_catalog = |name: &str| QualifiedName {
        namespace: Namespace::External {
            schema: "pg_catalog".into(),
        },
        name: name.into(),
    };
    assert_eq!(
        field(
            s,
            "orders",
            constraint("exclusion_window", ConstraintField::ExclusionOperators)
        )
        .fact(160015, 160015),
        Fact::Operators(&[
            OperatorSignature {
                operator: pg_catalog("&&"),
                left_type: Some(pg_catalog("anyrange")),
                right_type: Some(pg_catalog("anyrange")),
            },
            OperatorSignature {
                operator: pg_catalog("&&"),
                left_type: Some(pg_catalog("anyrange")),
                right_type: Some(pg_catalog("anyrange")),
            },
        ])
    );
    assert_eq!(
        field(
            s,
            "orders",
            FieldPath::Index {
                name: "uq".into(),
                owner: Some("uq".into()),
                field: IndexField::NullsNotDistinct
            }
        )
        .fact(160015, 160015),
        Fact::Boolean(true)
    );
    assert_eq!(
        field(
            s,
            "orders",
            FieldPath::Index {
                name: "exclusion_window".into(),
                owner: Some("exclusion_window".into()),
                field: IndexField::AccessMethod,
            }
        )
        .fact(160015, 160015),
        Fact::Text("gist")
    );
    let index_key = |name: &str, position, field| FieldPath::IndexKey {
        name: name.into(),
        owner: None,
        position,
        field,
    };
    assert_eq!(
        field(
            s,
            "orders",
            index_key("mixed", 0, IndexKeyField::SortOptions)
        )
        .fact(160015, 160015),
        Fact::Names(&["descending".into(), "nullsLast".into()])
    );
    assert_eq!(
        field(
            s,
            "orders",
            index_key("mixed", 1, IndexKeyField::Expression)
        )
        .fact(160015, 160015),
        Fact::Text("(quantity + 2)")
    );
    assert!(matches!(
        field(
            s,
            "orders",
            index_key("multiple", 0, IndexKeyField::Expression)
        )
        .fact(160015, 160015),
        Fact::NotComparable {
            reason: IncomparableReason::ExpressionOutsideSubset,
            ..
        }
    ));
    let exclusion_key = |position, field| FieldPath::IndexKey {
        name: "exclusion_window".into(),
        owner: Some("exclusion_window".into()),
        position,
        field,
    };
    assert_eq!(
        field(s, "orders", exclusion_key(0, IndexKeyField::Column)).fact(160015, 160015),
        Fact::Text("custom")
    );
    assert_eq!(
        field(s, "orders", exclusion_key(0, IndexKeyField::Opclass)).fact(160015, 160015),
        Fact::Reference(&pg_catalog("range_ops"))
    );
    assert_eq!(
        field(s, "orders", exclusion_key(0, IndexKeyField::SortOptions)).fact(160015, 160015),
        Fact::Null
    );
    assert_eq!(
        field(s, "orders", exclusion_key(1, IndexKeyField::Kind)).fact(160015, 160015),
        Fact::Text("expression")
    );
    assert_eq!(
        field(s, "orders", exclusion_key(1, IndexKeyField::Expression)).fact(160015, 160015),
        Fact::NotComparable {
            reason: IncomparableReason::ExternalDependency,
            raw: Some("int4range(quantity, (quantity + 1))"),
        }
    );
    assert_eq!(
        field(s, "orders", exclusion_key(1, IndexKeyField::Opclass)).fact(160015, 160015),
        Fact::Reference(&pg_catalog("range_ops"))
    );
    assert_eq!(
        field(s, "orders", exclusion_key(1, IndexKeyField::SortOptions)).fact(160015, 160015),
        Fact::Null
    );
    for f in s.fields() {
        let other = field(
            t,
            &s.table(f.table_oid).unwrap().identity.name,
            f.path.clone(),
        );
        assert_eq!(
            f.value.fact(160015, 160015),
            other.fact(160015, 160015),
            "{:?}",
            f.path
        );
    }
    let mut captures = captures.into_iter();
    let identity = ResultIdentity {
        job_id: "native".into(),
        result_id: "baseline".into(),
    };
    let now = std::time::Instant::now();
    let result = super::super::diff::compare(
        identity.clone(),
        captures.next().unwrap(),
        captures.next().unwrap(),
        &control,
        now,
    )
    .unwrap();
    drop(captures);
    assert_eq!(
        result.kind(),
        super::super::normalize::DifferenceKind::NotComparable
    );
    assert_eq!(
        result.metadata().consistency,
        SnapshotConsistency::SharedTransaction
    );
    let page = result
        .object_page(&identity, "baseline-page", 0, now)
        .unwrap();
    let decoded: serde_json::Value = serde_json::from_str(page.as_str()).unwrap();
    assert!(decoded["items"]
        .as_array()
        .unwrap()
        .iter()
        .all(|row| row["kind"] != "changed"));
    drop(page);
    drop(result);
    assert_eq!(budget.used(), 0);

    admin.client.batch_execute("ALTER TABLE \"Target\".orders ALTER COLUMN quantity SET DEFAULT 3; COMMENT ON COLUMN \"Target\".orders.quantity IS 'changed comment'").await.unwrap();
    let mut captures = capture_resolved(
        &spec,
        &[(Side::Source, &source), (Side::Target, &target)],
        &control,
        &budget,
    )
    .await
    .unwrap()
    .into_iter();
    let identity = ResultIdentity {
        job_id: "native".into(),
        result_id: "changed".into(),
    };
    let result = super::super::diff::compare(
        identity.clone(),
        captures.next().unwrap(),
        captures.next().unwrap(),
        &control,
        now,
    )
    .unwrap();
    drop(captures);
    assert_eq!(
        result.kind(),
        super::super::normalize::DifferenceKind::Changed
    );
    let page = result
        .object_page(&identity, "changed-page", 0, now)
        .unwrap();
    let decoded: serde_json::Value = serde_json::from_str(page.as_str()).unwrap();
    let orders = decoded["items"]
        .as_array()
        .unwrap()
        .iter()
        .find(|row| row["source"]["name"] == "orders")
        .unwrap();
    assert_eq!(orders["kind"], "changed");
    assert_eq!(orders["changedFields"], 2);
    assert!(orders["incomparableFields"].as_u64().unwrap() > 0);
    drop(page);
    drop(result);
    assert_eq!(budget.used(), 0);
    let missing = Endpoint {
        schema: "missing".into(),
        ..source.clone()
    };
    assert!(matches!(
        capture_resolved(&spec, &[(Side::Source, &missing)], &control, &budget).await,
        Err(CompareError::Unavailable)
    ));
    // Exact UTF-8 field cap, including worst-case sixfold JSON escaping.
    admin
        .client
        .batch_execute("CREATE SCHEMA limits; CREATE TABLE limits.t(id integer)")
        .await
        .unwrap();
    let limits = Endpoint {
        schema: "limits".into(),
        ..source.clone()
    };
    for (bytes, ok) in [(FIELD_BYTES, true), (FIELD_BYTES + 1, false)] {
        admin
            .client
            .batch_execute(&format!(
                "COMMENT ON TABLE limits.t IS {}",
                crate::quote_literal(&"\u{1}".repeat(bytes))
            ))
            .await
            .unwrap();
        let result = capture_resolved(&spec, &[(Side::Source, &limits)], &control, &budget).await;
        if ok {
            assert!(result.is_ok(), "{:?}", result.err());
        } else {
            assert!(matches!(
                result,
                Err(CompareError::LimitExceeded {
                    limit: Limit::FieldBytes
                })
            ));
        }
    }
    assert_eq!(budget.used(), 0);
    // A role can read a schema only when it can lock/read the complete table.
    admin
        .client
        .batch_execute(
            "CREATE ROLE capture_reader LOGIN; GRANT USAGE ON SCHEMA limits TO capture_reader",
        )
        .await
        .unwrap();
    let mut restricted = spec.clone();
    restricted.user = "capture_reader".into();
    assert!(matches!(
        capture_resolved(&restricted, &[(Side::Source, &limits)], &control, &budget).await,
        Err(CompareError::Unavailable)
    ));
    // Inventory and table caps are separate and reject complete captures.
    admin.client.batch_execute("CREATE SCHEMA inventory_cap; DO $$ BEGIN FOR i IN 1..2000 LOOP EXECUTE format('CREATE VIEW inventory_cap.v%s AS SELECT 1 AS id',i); END LOOP; END $$").await.unwrap();
    let schema = schema_oid(&admin.client, &control, "inventory_cap")
        .await
        .unwrap();
    assert_eq!(
        inventory(&admin.client, &control, schema)
            .await
            .unwrap()
            .len(),
        INVENTORY_ENTRIES
    );
    admin
        .client
        .batch_execute("CREATE VIEW inventory_cap.extra AS SELECT 1 AS id")
        .await
        .unwrap();
    assert!(matches!(
        inventory(&admin.client, &control, schema).await,
        Err(CompareError::LimitExceeded {
            limit: Limit::Inventory
        })
    ));
    admin.client.batch_execute("CREATE SCHEMA table_cap; DO $$ BEGIN FOR i IN 1..1000 LOOP EXECUTE format('CREATE TABLE table_cap.t%s ()',i); END LOOP; END $$").await.unwrap();
    let schema = schema_oid(&admin.client, &control, "table_cap")
        .await
        .unwrap();
    assert_eq!(
        inventory(&admin.client, &control, schema)
            .await
            .unwrap()
            .len(),
        TABLE_ENTRIES
    );
    admin
        .client
        .batch_execute("CREATE TABLE table_cap.extra ()")
        .await
        .unwrap();
    assert!(matches!(
        inventory(&admin.client, &control, schema).await,
        Err(CompareError::LimitExceeded {
            limit: Limit::Tables
        })
    ));
    // A candidate added while the reader waits for its pre-snapshot lock must
    // be discovered on the one fresh retry, never omitted as a deletion.
    admin
        .client
        .batch_execute("BEGIN; LOCK TABLE ONLY \"Source\".orders IN ACCESS EXCLUSIVE MODE")
        .await
        .unwrap();
    let endpoints = [(Side::Source, &source)];
    let reader = capture_resolved(&spec, &endpoints, &control, &budget);
    let writer = async {
        wait_for_lock(&admin.client, "\"Source\".orders").await;
        admin
            .client
            .batch_execute("CREATE TABLE \"Source\".added(id integer); COMMIT")
            .await
            .unwrap();
    };
    let (retried, ()) = tokio::join!(reader, writer);
    let retried = retried.unwrap();
    assert!(retried[0]
        .inventory
        .iter()
        .any(|r| r.identity.name == "added"));
    drop(retried);
    // Cancellation while waiting for a real relation lock stops the reader and
    // closes the transaction before its retained allocation is released.
    admin
        .client
        .batch_execute("BEGIN; LOCK TABLE ONLY \"Source\".orders IN ACCESS EXCLUSIVE MODE")
        .await
        .unwrap();
    let endpoints = [(Side::Source, &source)];
    let reader = capture_resolved(&spec, &endpoints, &control, &budget);
    let cancel = async {
        wait_for_lock(&admin.client, "\"Source\".orders").await;
        tx.send(true).unwrap();
    };
    let (cancelled, ()) = tokio::join!(reader, cancel);
    assert!(matches!(cancelled, Err(CompareError::Cancelled)));
    admin.client.batch_execute("ROLLBACK").await.unwrap();
    assert!(matches!(
        capture_resolved(&spec, &[(Side::Source, &source)], &control, &budget).await,
        Err(CompareError::Cancelled)
    ));
    assert_eq!(budget.used(), 0);
    admin.close().await;
}

async fn wait_for_lock(client: &Client, table: &str) {
    tokio::time::timeout(Duration::from_secs(5), async {
        loop {
            let row=client.query_one("SELECT EXISTS (SELECT 1 FROM pg_locks WHERE relation=$1::text::regclass AND NOT granted AND mode='AccessShareLock')", &[&table]).await.unwrap();
            if row.get::<_,bool>(0) { break; }
            tokio::time::sleep(Duration::from_millis(5)).await;
        }
    }).await.expect("reader reached its lock wait");
}

#[tokio::test]
#[ignore = "run infrastructure/test-db/schema-compare/native.py; owned disposable fixture only"]
async fn native_capture_normalizes_identifier_quoting() {
    use super::super::{diff, normalize::DifferenceKind, normalize::Fact};

    let port = std::env::var("DBUNK_SCHEMA_COMPARE_TEST_PORT")
        .expect("use native.py")
        .parse()
        .unwrap();
    let spec = fixture_spec(port);
    let admin = dedicated::connect(&spec, dedicated::NoticeSink::Ignore)
        .await
        .unwrap();
    admin
        .client
        .batch_execute(
            r#"CREATE SCHEMA quote_defaults;
            CREATE TABLE quote_defaults.orders (
                quantity integer, "Quoted name" integer,
                label text DEFAULT '"quantity"',
                CONSTRAINT positive CHECK (quantity > "Quoted name")
            );
            CREATE INDEX expression_idx ON quote_defaults.orders ((quantity + "Quoted name"))
                WHERE quantity > 0;"#,
        )
        .await
        .unwrap();
    admin.close().await;

    let (_tx, rx) = watch::channel(false);
    let control = CaptureControl::new(Instant::now() + Duration::from_secs(60), rx);
    let budget = Budget::default().result_scope();
    let mut captures = Vec::new();
    for (side, setting) in [(Side::Source, "off"), (Side::Target, "on")] {
        let connection = dedicated::connect(&spec, dedicated::NoticeSink::Ignore)
            .await
            .unwrap();
        connection
            .client
            .batch_execute(&format!("SET quote_all_identifiers = {setting}"))
            .await
            .unwrap();
        let endpoint = Endpoint {
            connection_id: setting.into(),
            schema: "quote_defaults".into(),
        };
        captures.extend(
            capture(
                &connection.client,
                &[(side, &endpoint)],
                &control,
                &budget,
                None,
            )
            .await
            .unwrap(),
        );
        connection.close().await;
    }

    // Required identifier quotes and literal contents survive normalization.
    for captured in &captures {
        let version = captured.metadata.server_version_num;
        assert_eq!(
            field(
                captured,
                "orders",
                FieldPath::Column {
                    name: "label".into(),
                    field: ColumnField::Default,
                },
            )
            .fact(version, version),
            Fact::Text("'\"quantity\"'::text")
        );
        assert_eq!(
            field(
                captured,
                "orders",
                FieldPath::Constraint {
                    name: "positive".into(),
                    field: ConstraintField::Expression,
                },
            )
            .fact(version, version),
            Fact::Text("(quantity > \"Quoted name\")")
        );
    }
    let target = captures.pop().unwrap();
    let source = captures.pop().unwrap();
    let comparison = diff::compare(
        ResultIdentity {
            job_id: "quoting".into(),
            result_id: "quoting".into(),
        },
        source,
        target,
        &control,
        std::time::Instant::now(),
    )
    .unwrap();
    assert_eq!(comparison.kind(), DifferenceKind::Equal);
}

#[test]
fn retained_capture_refuses_endpoint_and_child_limits_and_releases_budget() {
    let budget = Budget::default();
    let metadata = CaptureMetadata {
        endpoint: Endpoint {
            connection_id: "fixture".into(),
            schema: "public".into(),
        },
        server_version: "16.15".into(),
        server_version_num: 160015,
        captured_at: "now".into(),
    };
    let mut capture = CapturedEndpoint::new(metadata.clone(), &budget).unwrap();
    capture.oids.push(1);
    capture.inventory.push(InventoryEntry {
        identity: RelationIdentity {
            name: "t".into(),
            kind: RelationKind::Table,
        },
        eligibility: Eligibility::Eligible,
    });
    let row = || data::WireField {
        table_oid: 1,
        path: FieldPath::Table {
            field: TableField::Persistence,
        },
        fact: data::WireValue::Plain(CapturedValue::Null),
    };
    for _ in 0..MAX_VALUES {
        capture.push(row()).unwrap();
    }
    assert_eq!(
        capture.push(row()),
        Err(CompareError::LimitExceeded {
            limit: Limit::ChildFacts
        })
    );
    drop(capture);
    assert_eq!(budget.used(), 0);
    let mut capture = CapturedEndpoint::new(metadata, &budget).unwrap();
    capture.oids.push(1);
    capture.inventory.push(InventoryEntry {
        identity: RelationIdentity {
            name: "t".into(),
            kind: RelationKind::Table,
        },
        eligibility: Eligibility::Eligible,
    });
    loop {
        let next = data::WireField {
            table_oid: 1,
            path: FieldPath::Table {
                field: TableField::Comment,
            },
            fact: data::WireValue::Plain(CapturedValue::Text("x".repeat(FIELD_BYTES))),
        };
        if let Err(error) = capture.push(next) {
            assert_eq!(
                error,
                CompareError::LimitExceeded {
                    limit: Limit::EndpointBytes
                }
            );
            break;
        }
    }
    assert!(capture.retained_bytes() <= ENDPOINT_BYTES);
    drop(capture);
    assert_eq!(budget.used(), 0);
}
