use super::*;
fn column(number: i32, name: &str) -> StructureColumn {
    StructureColumn {
        number,
        name: name.into(),
        data_type: "numeric(40, 0)".into(),
        nullable: true,
        default_expression: None,
        comment: None,
        identity: StructureIdentityKind::None,
        generated: StructureGeneratedKind::None,
        primary_key_position: None,
        collation_schema: None,
        collation_name: None,
    }
}
fn snapshot() -> TableStructureSnapshot {
    TableStructureSnapshot {
        identity: TableIdentity {
            database_oid: 11,
            relation_oid: 22,
        },
        schema: "Quoted.Schema".into(),
        table: "t\"able".into(),
        kind: StructureRelationKind::Table,
        owner: "owner".into(),
        comment: None,
        server_version: 160014,
        captured_at: "2026-10-03 10:00:00+00".into(),
        columns: vec![column(1, "a"), column(3, "b")],
        primary_key: None,
        outbound: vec![],
        inbound: vec![],
        indexes: vec![],
        constraints: vec![],
        triggers: vec![],
        row_security: StructureRowSecurity {
            enabled: false,
            forced: false,
        },
        policies: vec![],
        privileges: vec![],
        rules: vec![],
        partition_key: None,
        is_partition: false,
        partition_bound: None,
        parents: vec![],
        partitions: vec![],
    }
}
fn capture(data: TableStructureSnapshot) -> Capture {
    Capture::new(data, Rc::new(Cell::new(0))).unwrap()
}
#[test]
fn parent_labels_follow_the_child_partition_relationship() {
    let mut data = snapshot();
    data.parents.push(StructureRelative {
        oid: 100,
        schema: "ancestors".into(),
        name: "parent".into(),
        sequence: 1,
        is_partition: false,
        bound: None,
    });
    assert_eq!(
        capture(data.clone())
            .row_label(Section::Parents, 0)
            .unwrap(),
        "\"ancestors\".\"parent\" · inheritance"
    );
    data.is_partition = true;
    data.partition_bound = Some("FOR VALUES FROM (0) TO (10)".into());
    assert_eq!(
        capture(data).row_label(Section::Parents, 0).unwrap(),
        "\"ancestors\".\"parent\" · partition"
    );
}
fn detail(c: &Capture, section: Section, index: usize) -> String {
    c.details(section, index).unwrap().unwrap()
}
#[test]
fn section_order_exact_unicode_numeric_text_and_null_empty_are_distinct() {
    assert_eq!(
        Section::ALL.map(Section::label),
        [
            "Overview",
            "Columns",
            "Primary key",
            "Foreign keys",
            "Referenced by",
            "Indexes",
            "Constraints",
            "Triggers",
            "Policies",
            "Relation grants",
            "Rules",
            "Parents",
            "Children"
        ]
    );
    let mut data = snapshot();
    data.comment = Some(String::new());
    data.columns[0].default_expression =
        Some("92233720368547758079223372036854775807::numeric".into());
    data.columns[0].comment = Some("Literal NULL\n雪 '\\'".into());
    data.columns[0].identity = StructureIdentityKind::ByDefault;
    data.columns[1].generated = StructureGeneratedKind::Stored;
    data.columns[1].default_expression = Some(String::new());
    data.columns[1].collation_schema = Some("pg_catalog".into());
    data.columns[1].collation_name = Some("C".into());
    let c = capture(data);
    assert_eq!(c.qualified_name(), "\"Quoted.Schema\".\"t\"\"able\"");
    assert_eq!(c.request().expected, Some(c.identity()));
    assert!(
        detail(&c, Section::Overview, 0).contains("Relation comment: empty text (0 UTF-8 bytes)")
    );
    let first = detail(&c, Section::Columns, 0);
    assert!(first.contains("92233720368547758079223372036854775807::numeric"));
    assert!(first.contains("Literal NULL\n雪 '\\'"));
    assert!(first.contains("Identity: GENERATED BY DEFAULT"));
    let second = detail(&c, Section::Columns, 1);
    assert!(second.contains("Comment: NULL (absent)"));
    assert!(second.contains("Default / generated expression: empty text"));
    assert!(second.contains("Generated: Stored"));
    assert!(second.contains("Collation name (text, 1 UTF-8 bytes):\nC"));
    assert!(c.details(Section::Columns, 2).unwrap().is_none());
    assert!(c.navigation(Section::Columns, 0).is_none());
}
fn foreign_key() -> StructureForeignKey {
    StructureForeignKey {
        oid: 44,
        name: "fk".into(),
        source_oid: 22,
        source_schema: "Quoted.Schema".into(),
        source_table: "t\"able".into(),
        target_oid: 55,
        target_schema: "Other.Schema".into(),
        target_table: "parent".into(),
        columns: vec![
            StructureKeyPair {
                source_number: 3,
                source: "b".into(),
                target_number: 8,
                target: "x".into(),
            },
            StructureKeyPair {
                source_number: 1,
                source: "a".into(),
                target_number: 2,
                target: "y".into(),
            },
        ],
        on_update: StructureReferentialAction::Cascade,
        on_delete: StructureReferentialAction::SetNull,
        match_type: "FULL".into(),
        deferrable: true,
        initially_deferred: true,
        validated: false,
    }
}
#[test]
fn primary_and_foreign_key_order_and_navigation_are_not_name_sorted() {
    let mut data = snapshot();
    data.columns[0].primary_key_position = Some(2);
    data.columns[1].primary_key_position = Some(1);
    data.primary_key = Some(StructurePrimaryKey {
        oid: 33,
        name: "pk".into(),
        columns: vec![
            StructureKeyColumn {
                number: 3,
                name: "b".into(),
            },
            StructureKeyColumn {
                number: 1,
                name: "a".into(),
            },
        ],
        deferrable: true,
        initially_deferred: false,
    });
    data.outbound.push(foreign_key());
    let mut inbound = foreign_key();
    inbound.oid = 45;
    inbound.source_oid = 66;
    inbound.source_schema = "incoming".into();
    inbound.source_table = "child".into();
    inbound.target_oid = 22;
    inbound.target_schema = data.schema.clone();
    inbound.target_table = data.table.clone();
    inbound.columns = vec![StructureKeyPair {
        source_number: 8,
        source: "source".into(),
        target_number: 3,
        target: "b".into(),
    }];
    data.inbound.push(inbound);
    let c = capture(data);
    let pk = detail(&c, Section::PrimaryKey, 0);
    assert!(
        pk.find("1. \"b\" (attribute 3)").unwrap() < pk.find("2. \"a\" (attribute 1)").unwrap()
    );
    let fk = detail(&c, Section::ForeignKeys, 0);
    assert!(fk.contains("1. \"b\" (attribute 3) → \"x\" (attribute 8)"));
    assert!(fk.contains("2. \"a\" (attribute 1) → \"y\" (attribute 2)"));
    for text in [
        "ON UPDATE: CASCADE",
        "ON DELETE: SET NULL",
        "MATCH: FULL",
        "Initially deferred: true",
        "Validated: false",
    ] {
        assert!(fk.contains(text));
    }
    assert_eq!(
        c.navigation(Section::ForeignKeys, 0),
        Some(Navigation {
            schema: "Other.Schema",
            table: "parent",
            identity: TableIdentity {
                database_oid: 11,
                relation_oid: 55
            }
        })
    );
    assert_eq!(
        c.navigation(Section::ReferencedBy, 0)
            .unwrap()
            .identity
            .relation_oid,
        66
    );
}
#[test]
fn index_expression_include_trigger_inheritance_and_rls_have_separate_fields() {
    let mut data = snapshot();
    data.indexes.push(StructureIndex {
        oid: 60,
        name: "expr_index".into(),
        method: "btree".into(),
        unique: true,
        primary: false,
        valid: false,
        ready: true,
        keys: vec![
            StructureIndexKey {
                position: 1,
                column_number: None,
                column_name: None,
                definition: "(a + 9223372036854775807)".into(),
                included: false,
            },
            StructureIndexKey {
                position: 2,
                column_number: Some(3),
                column_name: Some("b".into()),
                definition: "b".into(),
                included: true,
            },
        ],
        predicate: Some("a IS NOT NULL".into()),
        definition: "CREATE UNIQUE INDEX exact_definition".into(),
        constraint_oid: Some(61),
    });
    data.triggers.push(StructureTrigger {
        oid: 70,
        name: "t".into(),
        parent_trigger_oid: Some(69),
        timing: "BEFORE".into(),
        events: vec!["UPDATE".into(), "INSERT".into()],
        update_columns: vec![StructureKeyColumn {
            number: 3,
            name: "b".into(),
        }],
        level: "ROW".into(),
        enabled: StructureTriggerEnabled::Replica,
        function_oid: 71,
        function_schema: "func.schema".into(),
        function_name: "f".into(),
        definition: "CREATE TRIGGER exact_definition".into(),
    });
    data.row_security = StructureRowSecurity {
        enabled: true,
        forced: true,
    };
    data.policies.push(StructurePolicy {
        oid: 80,
        name: "p".into(),
        permissive: false,
        command: StructurePolicyCommand::Update,
        roles: vec!["role2".into(), "role1".into()],
        using_expression: None,
        with_check: Some(String::new()),
    });
    let c = capture(data);
    let index = detail(&c, Section::Indexes, 0);
    for text in [
        "Position 1: key",
        "Column attribute number (NULL means expression): NULL (absent)",
        "(a + 9223372036854775807)",
        "Position 2: INCLUDE",
        "Owning constraint OID: 61",
        "Valid: false",
        "Ready: true",
        "a IS NOT NULL",
        "CREATE UNIQUE INDEX exact_definition",
    ] {
        assert!(index.contains(text));
    }
    let trigger = detail(&c, Section::Triggers, 0);
    for text in [
        "Parent trigger OID (inherited/partition clone): 69",
        "Enabled: Replica",
        "Function: \"func.schema\".\"f\"",
        "Function OID: 71",
        "1. UPDATE\n2. INSERT",
        "UPDATE OF columns, in captured order (1):\n1. \"b\" (attribute 3)",
    ] {
        assert!(trigger.contains(text));
    }
    let policy = detail(&c, Section::Policies, 0);
    for text in [
        "Permissive: false",
        "Command: UPDATE",
        "Relation row security forced: true",
        "1. \"role2\"\n2. \"role1\"",
        "USING expression: NULL (absent)",
        "WITH CHECK expression: empty text",
    ] {
        assert!(policy.contains(text));
    }
}
#[test]
fn acl_scope_rules_constraints_and_partition_context_remain_explicit() {
    let mut data = snapshot();
    data.kind = StructureRelationKind::PartitionedTable;
    data.partition_key = Some("RANGE (a)".into());
    data.privileges.push(StructurePrivilege {
        grantor: "owner".into(),
        grantee: "PUBLIC".into(),
        privilege: "SELECT".into(),
        grantable: false,
    });
    data.rules.push(StructureRule {
        oid: 90,
        name: "r".into(),
        event: "UPDATE".into(),
        instead: true,
        enabled: StructureTriggerEnabled::Always,
        definition: "CREATE RULE exact_definition".into(),
    });
    data.constraints.push(StructureConstraint {
        oid: 91,
        name: "positive".into(),
        kind: "CHECK".into(),
        definition: "CHECK (a > 0) NOT VALID".into(),
        deferrable: false,
        initially_deferred: false,
        validated: false,
    });
    data.parents.push(StructureRelative {
        oid: 100,
        schema: "ancestors".into(),
        name: "parent".into(),
        sequence: 2,
        is_partition: false,
        bound: None,
    });
    data.partitions.push(StructureRelative {
        oid: 101,
        schema: "leaves".into(),
        name: "leaf".into(),
        sequence: 1,
        is_partition: true,
        bound: Some("FOR VALUES FROM (0) TO (10)".into()),
    });
    let c = capture(data);
    assert!(detail(&c, Section::Overview, 0).contains("RANGE (a)"));
    assert!(detail(&c, Section::RelationGrants, 0).contains(RELATION_ACL_SCOPE));
    assert!(
        c.empty_label(Section::RelationGrants)
            .contains("does not mean no access")
    );
    assert!(detail(&c, Section::Rules, 0).contains("INSTEAD: true\nEnabled: Always"));
    assert!(detail(&c, Section::Constraints, 0).contains("CHECK (a > 0) NOT VALID"));
    assert!(detail(&c, Section::Parents, 0).contains("Inheritance sequence: 2"));
    assert!(detail(&c, Section::Parents, 0).contains("Partition bound: NULL (absent)"));
    assert!(detail(&c, Section::Children, 0).contains("FOR VALUES FROM (0) TO (10)"));
    assert_eq!(
        c.navigation(Section::Children, 0)
            .unwrap()
            .identity
            .relation_oid,
        101
    );
    for section in Section::ALL {
        for index in 0..c.count(section) {
            assert!(c.row_label(section, index).unwrap().chars().count() <= MAX_LABEL_CHARS);
        }
    }
}
#[test]
fn actual_capacity_detail_overlap_and_atomic_refusal_are_charged_and_released() {
    let budget = Rc::new(Cell::new(0));
    let old = Capture::new(snapshot(), budget.clone()).unwrap();
    let old_bytes = old.retained_bytes();
    assert_eq!(budget.get(), old_bytes);
    let mut large = snapshot();
    large.columns[0].default_expression = Some("9".repeat(128 * 1024));
    let replacement = Capture::new(large, budget.clone()).unwrap();
    assert!(replacement.retained_bytes() > old_bytes + DETAIL_BYTE_ALLOWANCE * 128 * 1024);
    assert_eq!(budget.get(), old_bytes + replacement.retained_bytes());
    drop(replacement);
    assert_eq!(budget.get(), old_bytes);
    let held_elsewhere = SHARED_BYTES - old_bytes - 1;
    budget.set(budget.get() + held_elsewhere);
    assert!(Capture::new(snapshot(), budget.clone()).is_err());
    assert_eq!(old.count(Section::Columns), 2);
    assert_eq!(budget.get(), SHARED_BYTES - 1);
    budget.set(budget.get() - held_elsewhere);
    drop(old);
    assert_eq!(budget.get(), 0);
}
#[test]
fn malformed_or_oversized_capacity_never_changes_admission() {
    let budget = Rc::new(Cell::new(123));
    let mut invalid = snapshot();
    invalid.columns[1].number = 1;
    assert!(Capture::new(invalid, budget.clone()).is_err());
    assert_eq!(budget.get(), 123);
    let mut inflated = snapshot();
    inflated.columns[0].name.reserve(MAX_STRUCTURE_BYTES);
    assert!(Capture::new(inflated, budget.clone()).is_err());
    assert_eq!(budget.get(), 123);
    let mut counter = Counter {
        bytes: MAX_DETAIL_BYTES - 1,
        line_breaks: 7,
    };
    assert!(counter.write_str("雪").is_err());
    assert_eq!(counter.bytes, MAX_DETAIL_BYTES - 1);
    assert_eq!(counter.line_breaks, 7);
}

#[test]
fn newline_heavy_detail_refuses_before_formatting_and_preserves_previous_capture() {
    let budget = Rc::new(Cell::new(0));
    let old = Capture::new(snapshot(), budget.clone()).unwrap();
    let old_bytes = budget.get();
    let mut plain = snapshot();
    plain.columns[0].default_expression = Some("x".repeat(40_000));
    let plain_capture = Capture::new(plain, budget.clone()).unwrap();
    drop(plain_capture);
    assert_eq!(budget.get(), old_bytes);
    let mut lines = snapshot();
    lines.columns[0].default_expression = Some("\n".repeat(40_000));
    assert!(lines.checked_heap_bytes().is_some());
    assert!(Capture::new(lines, budget.clone()).is_err());
    assert_eq!(budget.get(), old_bytes);
    assert_eq!(old.count(Section::Columns), 2);
    assert!(old.details(Section::Columns, 0).unwrap().is_some());
    drop(old);
    assert_eq!(budget.get(), 0);
}
#[test]
fn selected_detail_rechecks_bytes_and_logical_runs_independently() {
    let mut data = snapshot();
    data.columns[0].default_expression = Some("x".repeat(4096));
    let mut c = capture(data);
    let bytes = c.largest_detail.bytes;
    c.data.columns[0].default_expression = Some("\n".repeat(4096));
    let mut measured = Counter::default();
    render(&c.data, Section::Columns, 0, &mut measured).unwrap();
    assert_eq!(measured.bytes, bytes);
    assert!(measured.line_breaks > c.largest_detail.line_breaks);
    assert!(c.details(Section::Columns, 0).is_err());
    c.data.columns[0].default_expression = Some("x".repeat(4097));
    assert!(c.details(Section::Columns, 0).is_err());
}
#[test]
fn line_count_covers_crlf_and_split_writes_without_utf8_byte_confusion() {
    let mut counter = Counter::default();
    counter.write_str("雪\r").unwrap();
    counter.write_str("\n\n").unwrap();
    assert_eq!(counter.bytes, 6);
    assert_eq!(counter.line_breaks, 3);
    assert_eq!(
        counter.editor_allowance(),
        Some(6 * DETAIL_BYTE_ALLOWANCE + 4 * LOGICAL_RUN_ALLOWANCE)
    );
}

#[test]
fn ddl_selection_carries_source_attnum_and_never_parses_display_names() {
    let capture = capture(snapshot());
    let selected = capture.ddl_selection(Section::Columns, 1).unwrap();
    assert_eq!(selected.attnum(), Some(3));
    let request = selected.request();
    assert_eq!(request.schema, "Quoted.Schema");
    assert_eq!(request.table, "t\"able");
    assert_eq!(request.column.as_deref(), Some("b"));
    assert_eq!(request.expected, Some(capture.identity()));
    let table = capture.ddl_selection(Section::Overview, 0).unwrap();
    assert!(table.request().column.is_none());
    assert!(table.attnum().is_none());
    assert!(capture.ddl_selection(Section::Columns, 2).is_none());
    assert!(capture.ddl_selection(Section::Indexes, 0).is_none());
}
#[test]
fn ddl_selection_refuses_view_and_inherited_or_partitioned_targets() {
    let mut data = snapshot();
    data.kind = StructureRelationKind::View;
    assert!(capture(data).ddl_selection(Section::Overview, 0).is_none());
    let mut data = snapshot();
    data.parents.push(StructureRelative {
        oid: 100,
        schema: "parent".into(),
        name: "rows".into(),
        sequence: 1,
        is_partition: false,
        bound: None,
    });
    assert!(capture(data).ddl_selection(Section::Columns, 0).is_none());
    let mut data = snapshot();
    data.kind = StructureRelationKind::PartitionedTable;
    assert!(capture(data).ddl_selection(Section::Overview, 0).is_none());
}
