//! Column operations and the column definition shared with `CREATE TABLE`.

use serde::{Deserialize, Serialize};

use super::common::*;
use super::fragment::validate_data_type;
use super::fragment::{validate_fragment, FragmentContext};
use super::{ObjectOperation, PgObjectError, RenderedOp};
use crate::{quote_double, quote_literal};

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(
    tag = "kind",
    rename_all = "camelCase",
    rename_all_fields = "camelCase"
)]
pub(crate) enum PgDefaultValue {
    Literal { value: String },
    Expression { sql: String },
}

#[derive(Debug, Serialize, Deserialize, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub(crate) enum PgIdentity {
    Always,
    ByDefault,
}

impl PgIdentity {
    pub(super) fn sql(self) -> &'static str {
        match self {
            Self::Always => "GENERATED ALWAYS AS IDENTITY",
            Self::ByDefault => "GENERATED BY DEFAULT AS IDENTITY",
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub(crate) struct NewColumnSpec {
    pub name: String,
    pub data_type: String,
    pub nullable: bool,
    pub default: Option<PgDefaultValue>,
    /// Identity columns are rendered `GENERATED … AS IDENTITY`; they must be
    /// non-nullable and carry no default. Absent in older payloads.
    #[serde(default)]
    pub identity: Option<PgIdentity>,
}

pub(super) fn validate_column_spec(
    op_index: usize,
    column: &NewColumnSpec,
) -> Result<(), PgObjectError> {
    require_name(op_index, "column", &column.name)?;
    validate_data_type(op_index, "column data type", &column.data_type)?;
    if let Some(PgDefaultValue::Expression { sql }) = &column.default {
        validate_fragment(
            op_index,
            "default expression",
            sql,
            FragmentContext::Embedded,
        )?;
    }
    if column.identity.is_some() {
        if column.nullable {
            return invalid(
                op_index,
                format!("identity column {} must be NOT NULL", column.name),
            );
        }
        if column.default.is_some() {
            return invalid(
                op_index,
                format!("identity column {} cannot have a default", column.name),
            );
        }
    }
    Ok(())
}

/// The SQL-bearing text of one column definition: its type and, for an
/// expression default, the expression.
pub(super) fn column_fragments(column: &NewColumnSpec) -> Vec<&str> {
    let mut values = vec![column.data_type.as_str()];
    if let Some(PgDefaultValue::Expression { sql }) = &column.default {
        values.push(sql);
    }
    values
}

pub(super) fn render_default(default: &PgDefaultValue) -> String {
    match default {
        PgDefaultValue::Literal { value } => quote_literal(value),
        PgDefaultValue::Expression { sql } => format!("({sql})"),
    }
}

pub(super) fn render_column_definition(column: &NewColumnSpec) -> String {
    let mut definition = format!("{} {}", quote_double(&column.name), column.data_type);
    if !column.nullable {
        definition.push_str(" NOT NULL");
    }
    if let Some(default) = &column.default {
        definition.push_str(" DEFAULT ");
        definition.push_str(&render_default(default));
    }
    if let Some(identity) = column.identity {
        definition.push(' ');
        definition.push_str(identity.sql());
    }
    definition
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub(crate) struct AddColumnOp {
    pub schema: String,
    pub table: String,
    pub column: NewColumnSpec,
}

impl ObjectOperation for AddColumnOp {
    fn validate(&self, op_index: usize) -> Result<(), PgObjectError> {
        let Self {
            schema,
            table,
            column,
        } = self;
        {
            require_table(op_index, schema, table)?;
            validate_column_spec(op_index, column)
        }
    }

    fn fragments(&self) -> Vec<&str> {
        column_fragments(&self.column)
    }

    fn render(&self, _op_index: usize) -> Result<RenderedOp, PgObjectError> {
        let Self {
            schema,
            table,
            column,
        } = self;
        let rendered = {
            let definition = render_column_definition(column);
            RenderedOp {
                sql: format!(
                    "ALTER TABLE {} ADD COLUMN {definition};",
                    qualified(schema, table)
                ),
                summary: format!("Add column {schema}.{table}.{}", column.name),
                destructive: !column.nullable,
                transactional: true,
            }
        };
        Ok(rendered)
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub(crate) struct DropColumnOp {
    pub schema: String,
    pub table: String,
    pub name: String,
    pub cascade: bool,
}

impl ObjectOperation for DropColumnOp {
    fn validate(&self, op_index: usize) -> Result<(), PgObjectError> {
        let Self {
            schema,
            table,
            name,
            ..
        } = self;
        {
            require_table(op_index, schema, table)?;
            require_name(op_index, "name", name)
        }
    }

    fn fragments(&self) -> Vec<&str> {
        Vec::new()
    }

    fn render(&self, _op_index: usize) -> Result<RenderedOp, PgObjectError> {
        let Self {
            schema,
            table,
            name,
            cascade,
        } = self;
        let rendered = {
            let behavior = if *cascade { "CASCADE" } else { "RESTRICT" };
            RenderedOp {
                sql: format!(
                    "ALTER TABLE {} DROP COLUMN {} {behavior};",
                    qualified(schema, table),
                    quote_double(name)
                ),
                summary: format!("Drop column {schema}.{table}.{name} ({behavior})"),
                destructive: true,
                transactional: true,
            }
        };
        Ok(rendered)
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub(crate) struct RenameColumnOp {
    pub schema: String,
    pub table: String,
    pub name: String,
    pub new_name: String,
}

impl ObjectOperation for RenameColumnOp {
    fn validate(&self, op_index: usize) -> Result<(), PgObjectError> {
        let Self {
            schema,
            table,
            name,
            new_name,
        } = self;
        {
            require_table(op_index, schema, table)?;
            require_name(op_index, "column", name)?;
            require_name(op_index, "new column name", new_name)
        }
    }

    fn fragments(&self) -> Vec<&str> {
        Vec::new()
    }

    fn render(&self, _op_index: usize) -> Result<RenderedOp, PgObjectError> {
        let Self {
            schema,
            table,
            name,
            new_name,
        } = self;
        let rendered = RenderedOp {
            sql: format!(
                "ALTER TABLE {} RENAME COLUMN {} TO {};",
                qualified(schema, table),
                quote_double(name),
                quote_double(new_name)
            ),
            summary: format!("Rename column {schema}.{table}.{name} to {new_name}"),
            destructive: false,
            transactional: true,
        };
        Ok(rendered)
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub(crate) struct AlterColumnTypeOp {
    pub schema: String,
    pub table: String,
    pub name: String,
    pub new_type: String,
    pub using: Option<String>,
}

impl ObjectOperation for AlterColumnTypeOp {
    fn validate(&self, op_index: usize) -> Result<(), PgObjectError> {
        let Self {
            schema,
            table,
            name,
            new_type,
            using,
        } = self;
        {
            require_table(op_index, schema, table)?;
            require_name(op_index, "column", name)?;
            validate_data_type(op_index, "new type", new_type)?;
            if let Some(using) = using {
                validate_fragment(
                    op_index,
                    "USING expression",
                    using,
                    FragmentContext::Embedded,
                )?;
            }
            Ok(())
        }
    }

    fn fragments(&self) -> Vec<&str> {
        std::iter::once(self.new_type.as_str())
            .chain(self.using.iter().map(String::as_str))
            .collect()
    }

    fn render(&self, _op_index: usize) -> Result<RenderedOp, PgObjectError> {
        let Self {
            schema,
            table,
            name,
            new_type,
            using,
        } = self;
        let rendered = RenderedOp {
            sql: format!(
                "ALTER TABLE {} ALTER COLUMN {} TYPE {}{};",
                qualified(schema, table),
                quote_double(name),
                new_type,
                using
                    .as_ref()
                    .map(|expression| format!(" USING {expression}"))
                    .unwrap_or_default()
            ),
            summary: format!("Change type of {schema}.{table}.{name} to {new_type}"),
            destructive: true,
            transactional: true,
        };
        Ok(rendered)
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub(crate) struct SetColumnNullableOp {
    pub schema: String,
    pub table: String,
    pub name: String,
    pub nullable: bool,
}

impl ObjectOperation for SetColumnNullableOp {
    fn validate(&self, op_index: usize) -> Result<(), PgObjectError> {
        let Self {
            schema,
            table,
            name,
            ..
        } = self;
        {
            require_table(op_index, schema, table)?;
            require_name(op_index, "name", name)
        }
    }

    fn fragments(&self) -> Vec<&str> {
        Vec::new()
    }

    fn render(&self, _op_index: usize) -> Result<RenderedOp, PgObjectError> {
        let Self {
            schema,
            table,
            name,
            nullable,
        } = self;
        let rendered = RenderedOp {
            sql: format!(
                "ALTER TABLE {} ALTER COLUMN {} {};",
                qualified(schema, table),
                quote_double(name),
                if *nullable {
                    "DROP NOT NULL"
                } else {
                    "SET NOT NULL"
                }
            ),
            summary: format!(
                "{} NOT NULL on {schema}.{table}.{name}",
                if *nullable { "Remove" } else { "Set" }
            ),
            destructive: !nullable,
            transactional: true,
        };
        Ok(rendered)
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub(crate) struct SetColumnDefaultOp {
    pub schema: String,
    pub table: String,
    pub name: String,
    pub default: Option<PgDefaultValue>,
}

impl ObjectOperation for SetColumnDefaultOp {
    fn validate(&self, op_index: usize) -> Result<(), PgObjectError> {
        let Self {
            schema,
            table,
            name,
            default,
        } = self;
        {
            require_table(op_index, schema, table)?;
            require_name(op_index, "column", name)?;
            if let Some(PgDefaultValue::Expression { sql }) = default {
                validate_fragment(
                    op_index,
                    "default expression",
                    sql,
                    FragmentContext::Embedded,
                )?;
            }
            Ok(())
        }
    }

    fn fragments(&self) -> Vec<&str> {
        match &self.default {
            Some(PgDefaultValue::Expression { sql }) => vec![sql],
            _ => Vec::new(),
        }
    }

    fn render(&self, _op_index: usize) -> Result<RenderedOp, PgObjectError> {
        let Self {
            schema,
            table,
            name,
            default,
        } = self;
        let rendered = RenderedOp {
            sql: format!(
                "ALTER TABLE {} ALTER COLUMN {} {};",
                qualified(schema, table),
                quote_double(name),
                default
                    .as_ref()
                    .map(|value| format!("SET DEFAULT {}", render_default(value)))
                    .unwrap_or_else(|| "DROP DEFAULT".to_string())
            ),
            summary: format!(
                "{} default on {schema}.{table}.{name}",
                if default.is_some() { "Set" } else { "Remove" }
            ),
            destructive: false,
            transactional: true,
        };
        Ok(rendered)
    }
}
