//! SQL is internal; table names never interpolate into statements. Array members
//! preserve catalog ordinality, including expression index keys and INCLUDEs.
//! Cast exported OIDs to bigint: PostgreSQL JSON encodes the oid type as text.
pub(super) const HEADER: &str = r#"SELECT 1::int AS components,
(SELECT oid::bigint FROM pg_catalog.pg_database WHERE datname=pg_catalog.current_database())AS database_oid,c.oid::bigint AS relation_oid,n.nspname::text AS schema,c.relname::text AS table,
CASE c.relkind WHEN 'r' THEN 'table' WHEN 'p' THEN 'partitioned_table' WHEN 'v' THEN 'view' WHEN 'm' THEN 'materialized_view' WHEN 'f' THEN 'foreign_table' ELSE 'unsupported' END AS kind,
pg_catalog.pg_get_userbyid(c.relowner)::text AS owner,pg_catalog.obj_description(c.oid,'pg_class')AS comment,
pg_catalog.current_setting('server_version_num')::integer AS server_version,pg_catalog.transaction_timestamp()::text AS captured_at,
c.relrowsecurity AS rls_enabled,c.relforcerowsecurity AS rls_forced,pg_catalog.pg_get_partkeydef(c.oid)AS partition_key,c.relispartition AS is_partition,CASE WHEN c.relispartition THEN pg_catalog.pg_get_expr(c.relpartbound,c.oid,true)END AS partition_bound
FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname=$2 ORDER BY c.oid"#;
pub(super) const COLUMNS: &str = r#"SELECT 1::int AS components,a.attnum::integer AS number,a.attname::text AS name,pg_catalog.format_type(a.atttypid,a.atttypmod) AS data_type,NOT a.attnotnull AS nullable,
pg_catalog.pg_get_expr(d.adbin,d.adrelid)AS default_expression,pg_catalog.col_description(a.attrelid,a.attnum)AS comment,
CASE a.attidentity WHEN '' THEN 'none' WHEN 'a' THEN 'always' WHEN 'd' THEN 'by_default' ELSE 'unknown' END AS identity,
CASE a.attgenerated WHEN '' THEN 'none' WHEN 's' THEN 'stored' WHEN 'v' THEN 'virtual' ELSE 'unknown' END AS generated,
(SELECT k.o::integer FROM pg_catalog.pg_constraint p CROSS JOIN LATERAL unnest(p.conkey)WITH ORDINALITY k(n,o) WHERE p.conrelid=a.attrelid AND p.contype='p' AND k.n=a.attnum)AS primary_key_position,
cn.nspname::text AS collation_schema,co.collname::text AS collation_name
FROM pg_catalog.pg_attribute a LEFT JOIN pg_catalog.pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum LEFT JOIN pg_catalog.pg_collation co ON co.oid=a.attcollation LEFT JOIN pg_catalog.pg_namespace cn ON cn.oid=co.collnamespace
WHERE a.attrelid=$1 AND a.attnum>0 AND NOT a.attisdropped ORDER BY a.attnum"#;
pub(super) const PRIMARY_KEY: &str = r#"SELECT (cardinality(c.conkey)>64) AS array_oversized,(1+cardinality(c.conkey))::int AS components,c.oid::bigint AS oid,c.conname::text AS name,
CASE WHEN cardinality(c.conkey)<=64 THEN (SELECT jsonb_agg(jsonb_build_object('number',a.attnum::int,'name',a.attname::text)ORDER BY k.o)FROM unnest(c.conkey)WITH ORDINALITY k(n,o)LEFT JOIN pg_catalog.pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.n)END AS columns,
c.condeferrable AS deferrable,c.condeferred AS initially_deferred FROM pg_catalog.pg_constraint c WHERE c.conrelid=$1 AND c.contype='p' ORDER BY c.oid"#;
pub(super) const FOREIGN_KEYS: &str = r#"SELECT (cardinality(c.conkey)>64) AS array_oversized,(1+cardinality(c.conkey))::int AS components,c.oid::bigint AS oid,c.conname::text AS name,c.conrelid::bigint AS source_oid,ns.nspname::text AS source_schema,s.relname::text AS source_table,c.confrelid::bigint AS target_oid,nt.nspname::text AS target_schema,t.relname::text AS target_table,
CASE WHEN cardinality(c.conkey)<=64 AND cardinality(c.conkey)=cardinality(c.confkey)THEN(SELECT jsonb_agg(jsonb_build_object('source_number',a.attnum::int,'source',a.attname::text,'target_number',b.attnum::int,'target',b.attname::text)ORDER BY k.o)FROM unnest(c.conkey,c.confkey)WITH ORDINALITY k(an,bn,o)LEFT JOIN pg_catalog.pg_attribute a ON a.attrelid=c.conrelid AND a.attnum=k.an LEFT JOIN pg_catalog.pg_attribute b ON b.attrelid=c.confrelid AND b.attnum=k.bn)END AS columns,
CASE c.confupdtype WHEN 'a' THEN 'no_action' WHEN 'r' THEN 'restrict' WHEN 'c' THEN 'cascade' WHEN 'n' THEN 'set_null' WHEN 'd' THEN 'set_default' ELSE 'unknown' END AS on_update,
CASE c.confdeltype WHEN 'a' THEN 'no_action' WHEN 'r' THEN 'restrict' WHEN 'c' THEN 'cascade' WHEN 'n' THEN 'set_null' WHEN 'd' THEN 'set_default' ELSE 'unknown' END AS on_delete,
CASE c.confmatchtype WHEN 'f' THEN 'FULL' WHEN 'p' THEN 'PARTIAL' WHEN 's' THEN 'SIMPLE' ELSE 'unknown' END AS match_type,c.condeferrable AS deferrable,c.condeferred AS initially_deferred,c.convalidated AS validated
FROM pg_catalog.pg_constraint c JOIN pg_catalog.pg_class s ON s.oid=c.conrelid JOIN pg_catalog.pg_namespace ns ON ns.oid=s.relnamespace JOIN pg_catalog.pg_class t ON t.oid=c.confrelid JOIN pg_catalog.pg_namespace nt ON nt.oid=t.relnamespace
WHERE c.contype='f' AND CASE WHEN $2::bool THEN c.confrelid=$1 ELSE c.conrelid=$1 END ORDER BY ns.nspname,s.relname,c.conname,c.oid"#;
pub(super) const INDEXES: &str = r#"SELECT (i.indnatts>32) AS array_oversized,(1+i.indnatts)::int AS components,i.indexrelid::bigint AS oid,c.relname::text AS name,am.amname::text AS method,i.indisunique AS unique,i.indisprimary AS primary,i.indisvalid AS valid,i.indisready AS ready,
CASE WHEN i.indnatts<=32 THEN (SELECT jsonb_agg(jsonb_build_object('position',k.o::int,'column_number',NULLIF(k.n,0)::int,'column_name',a.attname::text,'definition',pg_catalog.pg_get_indexdef(i.indexrelid,k.o::int,true),'included',k.o>i.indnkeyatts)ORDER BY k.o)FROM unnest(i.indkey::smallint[])WITH ORDINALITY k(n,o)LEFT JOIN pg_catalog.pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=k.n)END AS keys,
pg_catalog.pg_get_expr(i.indpred,i.indrelid)AS predicate,pg_catalog.pg_get_indexdef(i.indexrelid)AS definition,
(SELECT con.oid::bigint FROM pg_catalog.pg_constraint con WHERE con.conindid=i.indexrelid AND con.contype IN('p','u','x')LIMIT 1)AS constraint_oid
FROM pg_catalog.pg_index i JOIN pg_catalog.pg_class c ON c.oid=i.indexrelid JOIN pg_catalog.pg_am am ON am.oid=c.relam WHERE i.indrelid=$1 ORDER BY c.relname,c.oid"#;
pub(super) const CONSTRAINTS: &str = r#"SELECT 1::int AS components,c.oid::bigint AS oid,c.conname::text AS name,
CASE c.contype WHEN 'c' THEN 'check' WHEN 'u' THEN 'unique' WHEN 'x' THEN 'exclusion' WHEN 'p' THEN 'primary key' WHEN 'f' THEN 'foreign key' WHEN 'n' THEN 'not null' ELSE 'constraint' END AS kind,
pg_catalog.pg_get_constraintdef(c.oid,true)AS definition,c.condeferrable AS deferrable,c.condeferred AS initially_deferred,c.convalidated AS validated FROM pg_catalog.pg_constraint c WHERE c.conrelid=$1 ORDER BY c.conname,c.oid"#;
pub(super) const TRIGGERS: &str = r#"SELECT (cardinality(t.tgattr::smallint[])>1600) AS array_oversized,(5+cardinality(t.tgattr::smallint[]))::int AS components,t.oid::bigint AS oid,t.tgname::text AS name,NULLIF(t.tgparentid,0)::bigint AS parent_trigger_oid,CASE WHEN t.tgtype&2<>0 THEN 'BEFORE' WHEN t.tgtype&64<>0 THEN 'INSTEAD OF' ELSE 'AFTER' END AS timing,
array_remove(ARRAY[CASE WHEN t.tgtype&4<>0 THEN 'INSERT' END,CASE WHEN t.tgtype&8<>0 THEN 'DELETE' END,CASE WHEN t.tgtype&16<>0 THEN 'UPDATE' END,CASE WHEN t.tgtype&32<>0 THEN 'TRUNCATE' END],NULL)AS events,
CASE WHEN cardinality(t.tgattr::smallint[])<=1600 THEN coalesce((SELECT jsonb_agg(jsonb_build_object('number',a.attnum::int,'name',a.attname::text)ORDER BY k.o)FROM unnest(t.tgattr::smallint[])WITH ORDINALITY k(n,o)LEFT JOIN pg_catalog.pg_attribute a ON a.attrelid=t.tgrelid AND a.attnum=k.n),'[]'::jsonb)END AS update_columns,
CASE WHEN t.tgtype&1<>0 THEN 'ROW' ELSE 'STATEMENT' END AS level,
CASE t.tgenabled WHEN 'O' THEN 'origin' WHEN 'D' THEN 'disabled' WHEN 'R' THEN 'replica' WHEN 'A' THEN 'always' ELSE 'unknown' END AS enabled,p.oid::bigint AS function_oid,n.nspname::text AS function_schema,p.proname::text AS function_name,pg_catalog.pg_get_triggerdef(t.oid,true)AS definition
FROM pg_catalog.pg_trigger t JOIN pg_catalog.pg_proc p ON p.oid=t.tgfoid JOIN pg_catalog.pg_namespace n ON n.oid=p.pronamespace WHERE t.tgrelid=$1 AND NOT t.tgisinternal ORDER BY t.tgname,t.oid"#;
pub(super) const POLICIES: &str = r#"SELECT (cardinality(p.polroles)>1024) AS array_oversized,(1+cardinality(p.polroles))::int AS components,p.oid::bigint AS oid,p.polname::text AS name,p.polpermissive AS permissive,
CASE p.polcmd WHEN '*' THEN 'all' WHEN 'r' THEN 'select' WHEN 'a' THEN 'insert' WHEN 'w' THEN 'update' WHEN 'd' THEN 'delete' ELSE 'unknown' END AS command,
CASE WHEN cardinality(p.polroles)<=1024 THEN ARRAY(SELECT CASE WHEN r.oid=0 THEN 'public' ELSE pg_catalog.pg_get_userbyid(r.oid)::text END FROM unnest(p.polroles)WITH ORDINALITY r(oid,o)ORDER BY r.o)END AS roles,
pg_catalog.pg_get_expr(p.polqual,p.polrelid)AS using_expression,pg_catalog.pg_get_expr(p.polwithcheck,p.polrelid)AS with_check FROM pg_catalog.pg_policy p WHERE p.polrelid=$1 ORDER BY p.polname,p.oid"#;
pub(super) const PRIVILEGES: &str = r#"SELECT 1::int AS components,pg_catalog.pg_get_userbyid(a.grantor)::text AS grantor,CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_catalog.pg_get_userbyid(a.grantee)::text END AS grantee,a.privilege_type::text AS privilege,a.is_grantable AS grantable FROM pg_catalog.pg_class c CROSS JOIN LATERAL pg_catalog.aclexplode(c.relacl)a WHERE c.oid=$1 ORDER BY a.grantee,a.grantor,a.privilege_type,a.is_grantable"#;
pub(super) const RULES: &str = r#"SELECT 1::int AS components,r.oid::bigint AS oid,r.rulename::text AS name,CASE r.ev_type WHEN '1' THEN 'SELECT' WHEN '2' THEN 'UPDATE' WHEN '3' THEN 'INSERT' WHEN '4' THEN 'DELETE' ELSE 'unknown' END AS event,r.is_instead AS instead,
CASE r.ev_enabled WHEN 'O' THEN 'origin' WHEN 'D' THEN 'disabled' WHEN 'R' THEN 'replica' WHEN 'A' THEN 'always' ELSE 'unknown' END AS enabled,pg_catalog.pg_get_ruledef(r.oid,true)AS definition FROM pg_catalog.pg_rewrite r WHERE r.ev_class=$1 ORDER BY r.rulename,r.oid"#;
pub(super) const RELATIVES: &str = r#"SELECT 1::int AS components,c.oid::bigint AS oid,n.nspname::text AS schema,c.relname::text AS name,i.inhseqno::int AS sequence,c.relispartition AS is_partition,CASE WHEN c.relispartition THEN pg_catalog.pg_get_expr(c.relpartbound,c.oid,true)END AS bound FROM pg_catalog.pg_inherits i JOIN pg_catalog.pg_class c ON c.oid=CASE WHEN $2::bool THEN i.inhparent ELSE i.inhrelid END JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE CASE WHEN $2::bool THEN i.inhrelid ELSE i.inhparent END=$1 ORDER BY i.inhseqno,n.nspname,c.relname,c.oid"#;
